### ISSUE TITLE
Replace lib with node_modules or bower_components

### ISSUE THREAD

**Issue by jmeas** [rmurphey/js-assessment#106]
We're including some external deps [in the repo directly](https://github.com/rmurphey/js-assessment/tree/master/lib), which prob. isn't necessary with tools like npm and/or bower at our disposal.

I'm not anti-bower or anything, but I think this library might be a case where sticking to npm for simplicity / fewer moving parts could be beneficial.

**Comment by ashleygwilliams** [comment]
yessssss. p sure this is the next step in the refactor. i'm fine with just using npm. using 2 doesn't really add much value for us, and adds sig complexity for beginners.

i'll probs tackle this in the morning.

**Comment by rmurphey** [comment]
:+1: to just using npm please!

**Comment by jmeas** [comment]
Resolved in #112
