### ISSUE TITLE
add CHANGELOG

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#107]
because that makes sense

**Comment by jmeas** [comment]
:+1:

Are you thinking we should backfill it, or just start fresh @ 0.2.0?

**Comment by ashleygwilliams** [comment]
i think backfill, there was a 0.0.0 and a 0.1.0. i figure we combine them?

**Comment by jmeas** [comment]
Resolved in adfb4a0ee40bd11540dd3b2357c6e33eb9196612
