### ISSUE TITLE
do we support IE < 9?

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#109]
this will affect what version of jquery i include, see: http://jquery.com/download/

affects #106

**Comment by jmeas** [comment]
I was wondering the same thing yesterday, so I did a quick search through the code to see if I could infer anything. I concluded that yes, we do support < IE9, based on [this bit of code in the answers](https://github.com/rmurphey/js-assessment-answers/blob/master/app/arrays.js#L6-L14).

I suppose we could make it IE9+ if we wanted, tho'

**Comment by ashleygwilliams** [comment]
i wanna support < IE9. 1.11.3 it is~

**Comment by ashleygwilliams** [comment]
lol i just realized that that sounded super selfish. i meant that i'm down with maintaining support, esp since @jmeas agrees.

**Comment by jmeas** [comment]
> lol i just realized that that sounded super selfish. i meant that i'm down with maintaining support, esp since @jmeas agrees.

rofl

:+1:

**Comment by kadamwhite** [comment]
Haha :D +1!
