### ISSUE TITLE
bump to 0.3.0 

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#110]
i think we probs should, after removing require #108 , adding browser deps to package.json #106 , and then fixing #97. these are real large changes.

thoughts @jmeas?

**Comment by jmeas** [comment]
Sounds good to me

**Comment by ashleygwilliams** [comment]
#112 covers all these, so once it's merged we can bump

**Comment by jmeas** [comment]
Resolved in adfb4a0ee40bd11540dd3b2357c6e33eb9196612
