### ISSUE TITLE
minify browser deps?

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#111]
performance really isn't an issue and i think non-minified is helpful for debugging. mostly 100% on no here but thought i'd ask

**Comment by jmeas** [comment]
Yeah I don't think we get much by doin' this. It would also add a build step when running the tests which could be annoyin'. I'm leaning toward nah, as well

**Comment by ashleygwilliams** [comment]
i think most/all? of the browser deps ship with a min version, so the debugging thing is my main concern. sounds like we agree. woo!

**Comment by jmeas** [comment]
> i think most/all? of the browser deps ship with a min version

Ahhh, right.

> so the debugging thing is my main concern.

Def. a good point :+1:
