### ISSUE TITLE
Tests not loading in browser

### ISSUE THREAD

**Issue by merrickjeff** [rmurphey/js-assessment#126]
With the current master commit (4e39dc5), loading up localhost:4444 gives a blank page. The following is logged in Chrome dev tools console:

Navigated to http://localhost:4444/
(index):15 GET http://localhost:4444/node_modules/jquery/dist/jquery.js 
(index):17 GET http://localhost:4444/node_modules/chai/chai.js 
(index):22 Uncaught ReferenceError: chai is not defined(anonymous function) @ (index):22
arrays.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ arrays.js:6
async.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ async.js:6
bestPractices.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ bestPractices.js:6
count.js:13 Uncaught ReferenceError: describe is not defined(anonymous function) @ count.js:13
flowControl.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ flowControl.js:6
functions.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ functions.js:6
logicalOperators.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ logicalOperators.js:6
modules.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ modules.js:6
numbers.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ numbers.js:6
objects.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ objects.js:6
recursion.js:7 Uncaught ReferenceError: describe is not defined(anonymous function) @ recursion.js:7
regex.js:6 Uncaught ReferenceError: describe is not defined(anonymous function) @ regex.js:6
(index):56 GET http://localhost:35729/livereload.js net::ERR_CONNECTION_REFUSED

Did a bisect and the first bad commit is ce191d1c20b0246e8e65aba59e5c35c51ac16c80

**Comment by jmeas** [comment]
@merrickjeff did you delete your `node_modules` folder and run `npm install` again?

**Comment by merrickjeff** [comment]
Thanks, I had previously done an npm install. Didn't think to do it again. 

Works fine after doing npm install again.

**Comment by jmeas** [comment]
Glad to hear it, @merrickjeff! Gonna close this issue, then.
