### ISSUE TITLE
contributors guide

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#130]
as a first step to solving #129, after a long convo with @jmeas, i think creating a very specific contributing guide at `CONTRIBUTING.md` will help clarify both for ourselves and potential contributors what further extensions of js-assessment should be.

in keeping with https://github.com/rmurphey/js-assessment-answers/issues/31 re: style, i think that we should also focus on the technical details and styles of contributions in this doc

**Comment by kadamwhite** [comment]
+1! Contributing guides are great, and reduce a lot of confusion. I second that we be prescriptive about technical aspects as well, in the interest of maintaining this project's consistency.

**Comment by ashleygwilliams** [comment]
good question @kadamwhite. i think my plan is to whip up a basic structure/outline with some initial ideas and commit that to a branch. and hopefully from there do some inline discussion, and have people push to that branch if we end up assigning sections, or such.

what do you think? i'd like to keep this on github  (as opposed to a google doc) so it's transparent and all in one place, but perhaps that's unrealistic?

**Comment by kadamwhite** [comment]
Actually I love your suggestion, b/c I'd had the same concern about Google Docs! Let's give the branch approach a try, and we can reference this issue in PRs.

**Comment by ashleygwilliams** [comment]
cool! not sure if i'll get to it today, as i'm working on my jsconf talk a lot. but perhaps in a moment of procrastination :) either way, def something by the weekend

**Comment by jacobroufa** [comment]
@ashleygwilliams Any progress on this? Is there anything I might do to help? Also, seeing as we're both going to be at jsconf -- would you like to collaborate and have a small doc sprint for this project in person? If there's any input I can provide or anything I can help with, I'm happy to lend a hand! :+1:

**Comment by ashleygwilliams** [comment]
@jacobroufa that sounds awesome! let's do it.

**Comment by rmurphey** [comment]
I'm going to close this due to inactivity. A pull request is welcome!
