### ISSUE TITLE
js-koans: in-browser experience

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#131]
as referenced in #129, and mentioned in several convos with @rmurphey and @jmeas, i'm interested in building out a full in-browser experience for js-assessment.

inspiration originally comes from ruby-koans. http://rubykoans.com/

ruby koans supports both a CLI tool and an in-browser exp.

because this interface would require both this and the answers repository, i think i would propose creating a new repo for this. potentially called js-koans.

as our audience is dually beginners and employers/interviewers, my thought is that this would be a interface that a beginner could use alone, and a interviewer could pair on with an interviewee. 

partially bringing this up now as i have an opportunity to work on this with some folks with mozilla next week but want to get community input before diving in. so share your thoughts!

**Comment by Stephn-R** [comment]
I would recommend looking into [TogetherJS](https://togetherjs.com/) for providing support on pairing together an Interviewee with an Interviewer in realtime

**Comment by Stephn-R** [comment]
@ashleygwilliams overall, are you looking to put together a full, "in-browser" experience/web-app for which anyone can experience the tool?

**Comment by ashleygwilliams** [comment]
@Stephn-R yup. also: i think realtime pairing would be cool but definitely not MVP.

**Comment by Stephn-R** [comment]
@ashleygwilliams Totally, do you have a slack chat group yet for ```js-assessment```?

**Comment by ashleygwilliams** [comment]
there's a gitter! https://gitter.im/rmurphey/js-assessment. i'm usually at least lurking in there, if not actively participating. feel free to ping me there.

**Comment by ashleygwilliams** [comment]
i've created a repo for this, please move convo to issues there:
https://github.com/ashleygwilliams/js-koans
