### ISSUE TITLE
error when I npm start 

### ISSUE THREAD

**Issue by hsavit1** [rmurphey/js-assessment#143]
Server running 127.0.0.1:4444...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! js-assessment@0.3.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-assessment@0.3.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the js-assessment package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls js-assessment
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by rmurphey** [comment]
This would indicate that you already have another application running on port 4444 -- perhaps another instance of js-assessment itself? Use `ps -ef | grep node` to look for other node processes that might be conflicting.

**Comment by hsavit1** [comment]
thanks for your feedback! very insightful info
