### ISSUE TITLE
Best practices: declare functions safely passes by default on Firefox

### ISSUE THREAD

**Issue by vixus0** [rmurphey/js-assessment#144]
Browser: Firefox 41.0.2

The current default implementation of `exports.bestPracticesAnswers.functions` passes without any modifications when I expect it to fail. This is because Fx doesn't hoist function declarations within blocks, which I believe is technically correct according to the ECMA specs (only statements within blocks) but contrary to most other browsers. Not sure how to fix this really.

More info here:

* http://statichtml.com/2011/spidermonkey-function-hoisting.html
* http://stackoverflow.com/questions/27281445/javascript-function-hoisting-inside-of-if-statements

**Comment by rmurphey** [comment]
This also happens in Chrome. I might be inclined to remove this test.
