### ISSUE TITLE
Add links to reference material

### ISSUE THREAD

**Issue by rmurphey** [rmurphey/js-assessment#19]
The tests should include links to reference material so people can get some direction if they are stuck.

**Comment by ashleygwilliams** [comment]
we've agreed to add MDN links. PR forthcoming.

**Comment by jmeas** [comment]
A first step to get things started here could be to audit the source and create a list of all of the places that could maybe use references.

**Comment by cfjedimaster** [comment]
As just a random example of why this is still an issue - I'm currently looking at curtail in arrays.js. I did a quick Google thinking that perhaps it was something I had just not heard of, and I've still got absolutely no idea what is meant here. I think along with reference links, maybe even just a one line comment per test could be useful. Most folks know indexOf, but imagine this:

    //Given an array and a value, return the position in the array where the value is found, or -1 if not found at all.

**Comment by rmurphey** [comment]
Closing this due to age and ambiguity. Pull requests welcome to point people to good docs!
