### ISSUE TITLE
Any plans on upgrading this repo?

### ISSUE THREAD

**Issue by the-glima** [rmurphey/js-assessment#220]
Hi.

First things first: thanks for all the work you all put on this project. I remember forking this 4 years ago when I was learning JavaScript (still am).

Was wondering if you all have plans on upgrading with this repo? I can see open issues from 3/4 years ago. But the main reason that I'm asking this is that I was thinking to modernize this project a bit, bringing ES6, replacing dependencies, adding more modern test cases and (maybe) even adding TypeScript to help beginners (and non-beginners) to get faster feedback on what a method is expecting, etc... Also, I would like to add simple E2E tests that could assess another type of skill (HTPP, UI).

I'm just thinking out loud here. Actually, I was thinking about this a long time ago.

Thanks you.

**Comment by rmurphey** [comment]
Please feel free to fork if you think it would be useful. I'm no longer
maintaining this project.

**Comment by the-glima** [comment]
Ok. Thank you.
