### ISSUE TITLE
array: duplicates function unclear

### ISSUE THREAD

**Issue by markjuh** [rmurphey/js-assessment#64]
What should the duplicates function return?
1. All values in the array that have more than 1 occurrence.
2. All values that are left over after stripping away the first occurrence.

Examples:
1. [1, 1, 1, 4, 2, 2].duplicates = [1, 2]
2. [1, 1, 1, 4, 2, 2].duplicates = [1, 1, 2]

**Comment by jmeas** [comment]
Closing. This seems to be answered.
