### ISSUE TITLE
bug in the async tests?

### ISSUE THREAD

**Issue by gasolinewaltz** [rmurphey/js-assessment#79]
I have the code following code in app/async.js

```javascript
async : function(value) {

        return $.Deferred(function(deferred){
            //demonstrate that this is async
            setTimeout(function(){
                deferred.resolve(value);
            },500);
        }).promise();

    },

    manipulateRemoteData : function(url) {
        return $.Deferred(function(deferred) {
            $.getJSON(url, function(data) {
                var people = [];
                for (var i=0; i<data.people.length; i++) {
                    people.push(data.people[i].name);
                }
                deferred.resolve(people.sort());
            });
        }).promise();
    }
```
It appears that within the async function, when setTimeout() is firing after 200 milleseconds or so, three tests will appear under the "Async Behavior" section, one failing. The message tells me "you should understand how to use promises to handle asynchronicity", yet the error is specifically "Uncaught expected 0 to deeply equal 5..."

Is this a bug, or am I missing something?

**Comment by hirechrismeyers** [comment]
I can't reproduce this bug.

**Comment by jacalata** [comment]
This bug doesn't repro for me.

**Comment by rmurphey** [comment]
I can't repro this either. If this is still happening, please reopen with additional details such as browser, version, OS, etc.
