### ISSUE TITLE
about adding TDD styled tests

### ISSUE THREAD

**Issue by leobalter** [rmurphey/js-assessment#82]
I really like this project and it's probably one of the best resources of testing assessment.

Although, I would like to have the same tests in a "TDD style" (is there a name for it?).

I'm not thinking about a total replacement, it won't be a solution, but there's two reasonable options to discuss:

1. Add another dir with the same tests now with TDD styles.
2. Fork and replace (in the fork)

For the new style I don't have a specific preference, it may be anything like QUnit, Mocha (in TDD api), Substack's Tape, etc.

----

Edit: the goal is to also improve testing assessment in more freedom of expression. Tests are great in any code style.

**Comment by leobalter** [comment]
Recapping it, I think this is extra work without much gain. This repo is meant to provide js-assessment, and having different test styles won't improve it too much. Maybe this might lead to another project to provide tests assessment.

**Comment by rmurphey** [comment]
In hindsight I rather wish I'd used TDD style, to be honest. However, I agree: maintaining a separate dir would be annoying, and wouldn't add a ton to the aim of the repo. I also have a (completely unfounded) hunch that the current style might be more accessible to folks who haven't worked with tests before.
