### ISSUE TITLE
rewrite with updated dependencies

### ISSUE THREAD

**Issue by ashleygwilliams** [rmurphey/js-assessment#99]
would like to rewrite the scaffolding of this app with updated dependencies
- up to Express 4.x
- redo server/livereload with connect and watch in grunt
- update mocha, maybe replace expect with chai

the old deps are making the app behave strangely in newer versions of node (#97). i start working on this in #98 and realized that to do this right, the best option would be to update all the deps.

i estimate this will take me a day. after we do this, we can bump up the version of this js-assessment package to 0.2.0. i'm pretty sure that the interface of the application can remain basically unchanged, except we won't use node bin/serve, but probably a more classic node index.js, or npm start so users shouldn't see much change expect for bugs disappearing.

thoughts, @rmurphey @jmeas @kadamwhite ?

**Comment by kadamwhite** [comment]
Sounds good, @ashleygwilliams -- do you want one of us to tackle this, or do you have bandwidth right now? I'd put in a strong +1 for `npm start` (and `npm test`, too, for that measure, once we figure out the command-line testing issues), as an easy way to get up and running without needing to install any global deps.

**Comment by ashleygwilliams** [comment]
@kadamwhite i basically already have it done :) so i'm happy to do it, but i wanted to get ya'lls opinion

**Comment by jmeas** [comment]
Sounds good to me. I could even see this update being reason to bump the version to v1.0.0.

**Comment by rmurphey** [comment]
:+1: from me! This has been in need of an upgrade for a long while.

**Comment by kadamwhite** [comment]
@jmeas IMO the 1.0 bump would be best matched by a milestone in the perceived scope of what's being tested; if this was a module, for example, I imagine that the content would be an API upgrade and the infrastructural tooling shouldn't change that API.

**Comment by rmurphey** [comment]
I am +0.5 on bumping to 1.0.0. The fact that this will now be following established, current best practices may be a good enough reason to call it 1.0 -- everything before now has just been a draft :)

**Comment by ashleygwilliams** [comment]
i'm always hesitant to update to 1.0.0- i'd say let's stick with 0.x and once we've finished our first sweep of cleaning *everything* up, aim for a 1.0.0, probably around june? maybe we should all have a chat about this, make a roadmap?

**Comment by jmeas** [comment]
Sounds reasonable to me. Let's hold off on the 1.0 update, then.
